/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SosRouteImport } from './routes/sos'
import { Route as FamilyDashboardRouteImport } from './routes/family.dashboard'
import { Route as FamilyInsightsRouteImport } from './routes/family.insights'
import { Route as FamilyMedicinesRouteImport } from './routes/family.medicines'
import { Route as FamilyParentsRouteImport } from './routes/family.parents'
import { Route as FamilyProfileRouteImport } from './routes/family.profile'
import { Route as OnboardingFamilyRouteImport } from './routes/onboarding.family'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as ParentAiRouteImport } from './routes/parent.ai'
import { Route as ParentFamilyRouteImport } from './routes/parent.family'
import { Route as ParentHealthRouteImport } from './routes/parent.health'
import { Route as ParentHomeRouteImport } from './routes/parent.home'
import { Route as ParentProfileRouteImport } from './routes/parent.profile'
import { Route as SetupCompleteRouteImport } from './routes/setup.complete'
import { Route as FamilyAppointmentsNewRouteImport } from './routes/family.appointments.new'
import { Route as FamilyParentsIdRouteImport } from './routes/family.parents.$id'
import { Route as ParentMedicineScanRouteImport } from './routes/parent.medicine.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDashboardRoute = FamilyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyInsightsRoute = FamilyInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyMedicinesRoute = FamilyMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyParentsRoute = FamilyParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyProfileRoute = FamilyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FamilyRoute,
} as any)
const OnboardingFamilyRoute = OnboardingFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)
const ParentAiRoute = ParentAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFamilyRoute = ParentFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => ParentRoute,
} as any)
const ParentHealthRoute = ParentHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ParentRoute,
} as any)
const ParentHomeRoute = ParentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProfileRoute = ParentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParentRoute,
} as any)
const SetupCompleteRoute = SetupCompleteRouteImport.update({
  id: '/setup/complete',
  path: '/setup/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyAppointmentsNewRoute = FamilyAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyParentsIdRoute = FamilyParentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FamilyParentsRoute,
} as any)
const ParentMedicineScanRoute = ParentMedicineScanRouteImport.update({
  id: '/medicine/scan',
  path: '/medicine/scan',
  getParentRoute: () => ParentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/family': typeof FamilyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/insights': typeof FamilyInsightsRoute
  '/family/medicines': typeof FamilyMedicinesRoute
  '/family/parents': typeof FamilyParentsRouteWithChildren
  '/family/profile': typeof FamilyProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/parent/ai': typeof ParentAiRoute
  '/parent/family': typeof ParentFamilyRoute
  '/parent/health': typeof ParentHealthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/profile': typeof ParentProfileRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/family/appointments/new': typeof FamilyAppointmentsNewRoute
  '/family/parents/$id': typeof FamilyParentsIdRoute
  '/parent/medicine/scan': typeof ParentMedicineScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/family': typeof FamilyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/insights': typeof FamilyInsightsRoute
  '/family/medicines': typeof FamilyMedicinesRoute
  '/family/parents': typeof FamilyParentsRouteWithChildren
  '/family/profile': typeof FamilyProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/parent/ai': typeof ParentAiRoute
  '/parent/family': typeof ParentFamilyRoute
  '/parent/health': typeof ParentHealthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/profile': typeof ParentProfileRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/family/appointments/new': typeof FamilyAppointmentsNewRoute
  '/family/parents/$id': typeof FamilyParentsIdRoute
  '/parent/medicine/scan': typeof ParentMedicineScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof CallsRoute
  '/family': typeof FamilyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/family/dashboard': typeof FamilyDashboardRoute
  '/family/insights': typeof FamilyInsightsRoute
  '/family/medicines': typeof FamilyMedicinesRoute
  '/family/parents': typeof FamilyParentsRouteWithChildren
  '/family/profile': typeof FamilyProfileRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/parent/ai': typeof ParentAiRoute
  '/parent/family': typeof ParentFamilyRoute
  '/parent/health': typeof ParentHealthRoute
  '/parent/home': typeof ParentHomeRoute
  '/parent/profile': typeof ParentProfileRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/family/appointments/new': typeof FamilyAppointmentsNewRoute
  '/family/parents/$id': typeof FamilyParentsIdRoute
  '/parent/medicine/scan': typeof ParentMedicineScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calls'
    | '/family'
    | '/forgot-password'
    | '/notifications'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/reset-password'
    | '/sos'
    | '/family/dashboard'
    | '/family/insights'
    | '/family/medicines'
    | '/family/parents'
    | '/family/profile'
    | '/onboarding/family'
    | '/onboarding/profile'
    | '/parent/ai'
    | '/parent/family'
    | '/parent/health'
    | '/parent/home'
    | '/parent/profile'
    | '/setup/complete'
    | '/family/appointments/new'
    | '/family/parents/$id'
    | '/parent/medicine/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calls'
    | '/family'
    | '/forgot-password'
    | '/notifications'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/reset-password'
    | '/sos'
    | '/family/dashboard'
    | '/family/insights'
    | '/family/medicines'
    | '/family/parents'
    | '/family/profile'
    | '/onboarding/family'
    | '/onboarding/profile'
    | '/parent/ai'
    | '/parent/family'
    | '/parent/health'
    | '/parent/home'
    | '/parent/profile'
    | '/setup/complete'
    | '/family/appointments/new'
    | '/family/parents/$id'
    | '/parent/medicine/scan'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calls'
    | '/family'
    | '/forgot-password'
    | '/notifications'
    | '/onboarding'
    | '/parent'
    | '/pricing'
    | '/reset-password'
    | '/sos'
    | '/family/dashboard'
    | '/family/insights'
    | '/family/medicines'
    | '/family/parents'
    | '/family/profile'
    | '/onboarding/family'
    | '/onboarding/profile'
    | '/parent/ai'
    | '/parent/family'
    | '/parent/health'
    | '/parent/home'
    | '/parent/profile'
    | '/setup/complete'
    | '/family/appointments/new'
    | '/family/parents/$id'
    | '/parent/medicine/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallsRoute: typeof CallsRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SosRoute: typeof SosRoute
  SetupCompleteRoute: typeof SetupCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/dashboard': {
      id: '/family/dashboard'
      path: '/dashboard'
      fullPath: '/family/dashboard'
      preLoaderRoute: typeof FamilyDashboardRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/insights': {
      id: '/family/insights'
      path: '/insights'
      fullPath: '/family/insights'
      preLoaderRoute: typeof FamilyInsightsRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/medicines': {
      id: '/family/medicines'
      path: '/medicines'
      fullPath: '/family/medicines'
      preLoaderRoute: typeof FamilyMedicinesRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/parents': {
      id: '/family/parents'
      path: '/parents'
      fullPath: '/family/parents'
      preLoaderRoute: typeof FamilyParentsRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/profile': {
      id: '/family/profile'
      path: '/profile'
      fullPath: '/family/profile'
      preLoaderRoute: typeof FamilyProfileRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/onboarding/family': {
      id: '/onboarding/family'
      path: '/family'
      fullPath: '/onboarding/family'
      preLoaderRoute: typeof OnboardingFamilyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/parent/ai': {
      id: '/parent/ai'
      path: '/ai'
      fullPath: '/parent/ai'
      preLoaderRoute: typeof ParentAiRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/family': {
      id: '/parent/family'
      path: '/family'
      fullPath: '/parent/family'
      preLoaderRoute: typeof ParentFamilyRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/health': {
      id: '/parent/health'
      path: '/health'
      fullPath: '/parent/health'
      preLoaderRoute: typeof ParentHealthRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/home': {
      id: '/parent/home'
      path: '/home'
      fullPath: '/parent/home'
      preLoaderRoute: typeof ParentHomeRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/profile': {
      id: '/parent/profile'
      path: '/profile'
      fullPath: '/parent/profile'
      preLoaderRoute: typeof ParentProfileRouteImport
      parentRoute: typeof ParentRoute
    }
    '/setup/complete': {
      id: '/setup/complete'
      path: '/setup/complete'
      fullPath: '/setup/complete'
      preLoaderRoute: typeof SetupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/appointments/new': {
      id: '/family/appointments/new'
      path: '/appointments/new'
      fullPath: '/family/appointments/new'
      preLoaderRoute: typeof FamilyAppointmentsNewRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/parents/$id': {
      id: '/family/parents/$id'
      path: '/$id'
      fullPath: '/family/parents/$id'
      preLoaderRoute: typeof FamilyParentsIdRouteImport
      parentRoute: typeof FamilyParentsRoute
    }
    '/parent/medicine/scan': {
      id: '/parent/medicine/scan'
      path: '/medicine/scan'
      fullPath: '/parent/medicine/scan'
      preLoaderRoute: typeof ParentMedicineScanRouteImport
      parentRoute: typeof ParentRoute
    }
  }
}

interface FamilyParentsRouteChildren {
  FamilyParentsIdRoute: typeof FamilyParentsIdRoute
}

const FamilyParentsRouteChildren: FamilyParentsRouteChildren = {
  FamilyParentsIdRoute: FamilyParentsIdRoute,
}

const FamilyParentsRouteWithChildren = FamilyParentsRoute._addFileChildren(
  FamilyParentsRouteChildren,
)

interface FamilyRouteChildren {
  FamilyDashboardRoute: typeof FamilyDashboardRoute
  FamilyInsightsRoute: typeof FamilyInsightsRoute
  FamilyMedicinesRoute: typeof FamilyMedicinesRoute
  FamilyParentsRoute: typeof FamilyParentsRouteWithChildren
  FamilyProfileRoute: typeof FamilyProfileRoute
  FamilyAppointmentsNewRoute: typeof FamilyAppointmentsNewRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyDashboardRoute: FamilyDashboardRoute,
  FamilyInsightsRoute: FamilyInsightsRoute,
  FamilyMedicinesRoute: FamilyMedicinesRoute,
  FamilyParentsRoute: FamilyParentsRouteWithChildren,
  FamilyProfileRoute: FamilyProfileRoute,
  FamilyAppointmentsNewRoute: FamilyAppointmentsNewRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface OnboardingRouteChildren {
  OnboardingFamilyRoute: typeof OnboardingFamilyRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingFamilyRoute: OnboardingFamilyRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface ParentRouteChildren {
  ParentAiRoute: typeof ParentAiRoute
  ParentFamilyRoute: typeof ParentFamilyRoute
  ParentHealthRoute: typeof ParentHealthRoute
  ParentHomeRoute: typeof ParentHomeRoute
  ParentProfileRoute: typeof ParentProfileRoute
  ParentMedicineScanRoute: typeof ParentMedicineScanRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAiRoute: ParentAiRoute,
  ParentFamilyRoute: ParentFamilyRoute,
  ParentHealthRoute: ParentHealthRoute,
  ParentHomeRoute: ParentHomeRoute,
  ParentProfileRoute: ParentProfileRoute,
  ParentMedicineScanRoute: ParentMedicineScanRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallsRoute: CallsRoute,
  FamilyRoute: FamilyRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SosRoute: SosRoute,
  SetupCompleteRoute: SetupCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
